### ISSUE TITLE
References are not sorted in the way they appear in the narrative

### ISSUE THREAD

**Issue by prtkm** [ndlib/nddiss#11]
Hi Don,

I just started writing my thesis and noticed that the references are not sorted in the order the appear in the narrative. Is this a feature? It seems odd to me that the first reference that appears in the document is number 20. See example below:

![screen shot 2019-01-30 at 8 29 37 pm](https://user-images.githubusercontent.com/2263899/52028834-c8f66f80-24cd-11e9-9ba1-e39bd15d4c01.png)

Here is how they should appear if sorted (it looks a lot clearer IMO). I created a pull request that addresses this issue.

![screen shot 2019-01-30 at 8 31 22 pm](https://user-images.githubusercontent.com/2263899/52028878-065afd00-24ce-11e9-850c-3d3bcadb7d63.png)

**Comment by dbrower** [comment]
Hi Prateek! The behavior you see is expected. The numbers come from the ordering in the bibliography, which is sorted by author last name. I know there are differences in citation formats between disciplines, so please feel free to modify the dissertation style to suit your needs. Maybe this sorting behavior could be turned into an option on the class? Thanks for reaching out.

**Comment by prtkm** [comment]
Ah I see. Sorting by author last name would make sense for author-date style citations (class option textrefs). I think sorting by order of appearance is more appropriate for numbered citations (class option numrefs).
