### ISSUE TITLE
Justification of figure captions

### ISSUE THREAD

**Issue by mquevill** [ndlib/nddiss#16]
According to the author resources, figure captions should be justified. Since the style doesn't use the proper `caption` package, using `\captionsetup{justification=justified}` does not seem to work. Even the table notes in `threeparttable` are justified, so the figure captions look even more out of place.

Is there a way to manually force this justification? Or would it need to be applied to the .cls file?

**Comment by mquevill** [comment]
I modified the following line by removing the `\centering`, which gives me the desired effect.
https://github.com/ndlib/nddiss/blob/6bea0492953f0a8ddf5d8e64980f4d03ca05060e/nddiss2e.cls#L665

I would argue that Table "captions" should still be centered, since they are formatted like chapter headings.

**Comment by dbrower** [comment]
I've often wondered if it is possible to use the caption package? But that seems like a complete rewrite of the whole style to use modern packages for everything.
